name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  run-unittests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Unittests
        run: |
          pip3 install --ignore-installed httplib2
          pip3 install .
          cd tests
          echo '${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}' > service_account_credentials.json
          python3 -m unittest 

  update-pypi-remote:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' &&  startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and upload to Pypi remote
        env:
          VERSION: ${{ GITHUB_REF_NAME }}
        run: |
          pip3 install twine
          python3 setup.py sdist
          twine check dist/*
          twine upload --username=${{ secrets.PYPI_USER }} --password=${{ secrets.PYPI_PASSWORD }} dist/*
