name: Tests
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-unittests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Unittests
        run: |
          pip3 install --ignore-installed httplib2
          pip3 install .
          cd tests
          echo '${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}' > service_account_credentials.json
          python3 -m unittest 
      - nme: envtest
        env:
          VERSION: $GITHUB_REF_NAME
        run: |
          echo $VERSION

